package frc.tecdroid3354.subsystems.angularPosition

import edu.wpi.first.units.measure.Angle
import edu.wpi.first.wpilibj.Alert
import edu.wpi.first.wpilibj2.command.SubsystemBase
import frc.tecdroid3354.constants.SubsystemsControlGains
import frc.tecdroid3354.constants.SubsystemsPresetTargets
import frc.tecdroid3354.constants.SubsystemsTunableTargets
import frc.tecdroid3354.utils.degrees
import frc.tecdroid3354.utils.devices.MotorIOs.MotorIOInputsAutoLogged
import org.littletonrobotics.junction.Logger

class JointSubsystem(private val io: JointIO): SubsystemBase(JointConstants.Telemetry.SUBSYSTEM_TAB) {
    // Auto generated by @AutoLog in IO layer
    private val inputs: JointIOInputsAutoLogged = JointIOInputsAutoLogged()
    private val leadMotorInputs: MotorIOInputsAutoLogged = MotorIOInputsAutoLogged()
    private val followerMotorInputs: MotorIOInputsAutoLogged = MotorIOInputsAutoLogged()

    private val leadMotorDisconnectedAlert: Alert =
        Alert(JointConstants.Telemetry.LEAD_MOTOR_CONNECTION_ALERT_TAB, Alert.AlertType.kError)
    private val followerMotorDisconnectedAlert: Alert =
        Alert(JointConstants.Telemetry.FOLLOWER_MOTOR_CONNECTION_ALERT_TAB, Alert.AlertType.kError)

    init {
        io.initialMotorConfiguration()
    }

    override fun periodic() {
        io.updateJointInputs(inputs, leadMotorInputs, followerMotorInputs)
        Logger.processInputs(JointConstants.Telemetry.SUBSYSTEM_TAB, inputs)
        Logger.processInputs(JointConstants.Telemetry.LEAD_MOTOR_INPUTS_TAB, leadMotorInputs)
        Logger.processInputs(JointConstants.Telemetry.FOLLOWER_MOTOR_INPUTS_TAB, followerMotorInputs)

        // Updates each alert based on the retrieved connectivity status of this cycle.
        // alert = notConnected ? true : false
        leadMotorDisconnectedAlert.set(leadMotorInputs.isConnected.not())
        followerMotorDisconnectedAlert.set(followerMotorInputs.isConnected.not())

        // Update 2d and 3d (if applicable) visualization of the mechanism. Mechanism is logged inside the method.
        //visualizer.updateElevatorVisualization(inputs.elevatorDisplacement)

        if (SubsystemsControlGains.JOINT_MOTOR_PRIMARY_GAINS.hadTunableUpdated()) {
            io.updateJointMotorsControlGains(0) // Updates slot0 because is the primary set
        }

        if (SubsystemsTunableTargets.JOINT_MANUAL_TARGET_DEGREES.hasChanged(hashCode())) {
            io.updateJointManualPosition(SubsystemsTunableTargets.JOINT_MANUAL_TARGET_DEGREES.get().degrees)
        }
    }

    fun setJointManualPosition(): Runnable {
        return io.setJointManualPosition()
    }

    fun setJointPosition(jointPosition: Angle): Runnable {
        return io.setJointPosition(jointPosition)
    }

    fun setJointIdlePosition(): Runnable {
        return io.setJointPosition(SubsystemsPresetTargets.JOINT_IDLE_ANGLE)
    }

    fun setJointHomePosition(): Runnable {
        return io.setJointPosition(SubsystemsPresetTargets.JOINT_HOME_ANGLE)
    }

    fun stopJoint(): Runnable {
        return io.stopJoint()
    }

    fun getJointPosition(): Angle = inputs.jointActualPosition

    fun coastJoint(): Runnable {
        return io.coastJointMotors()
    }

    fun brakeJoint(): Runnable {
        return io.brakeJointMotors()
    }
}